// <auto-generated />
using System;
using DashBoard.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DashBoard.API.Migrations.Mysql
{
    [DbContext(typeof(MysqlContext))]
    [Migration("20240309172923_v1")]
    partial class v1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("DashBoard.API.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeNumber")
                        .HasColumnType("int unsigned")
                        .HasColumnName("Employee Number");

                    b.Property<int>("PayRatesIdPayRates")
                        .HasColumnType("int")
                        .HasColumnName("Pay Rates_idPay Rates");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("First Name");

                    b.Property<int>("IdEmployee")
                        .HasColumnType("int")
                        .HasColumnName("idEmployee");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("Last Name");

                    b.Property<decimal?>("PaidLastYear")
                        .HasColumnType("decimal(2,0)")
                        .HasColumnName("Paid Last Year");

                    b.Property<decimal?>("PaidToDate")
                        .HasColumnType("decimal(2,0)")
                        .HasColumnName("Paid To Date");

                    b.Property<string>("PayRate")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("Pay Rate");

                    b.Property<decimal>("Ssn")
                        .HasColumnType("decimal(10,0)")
                        .HasColumnName("SSN");

                    b.Property<int?>("VacationDays")
                        .HasColumnType("int")
                        .HasColumnName("Vacation Days");

                    b.HasKey("EmployeeNumber", "PayRatesIdPayRates");

                    b.HasIndex(new[] { "EmployeeNumber" }, "Employee Number_UNIQUE")
                        .IsUnique();

                    b.HasIndex(new[] { "PayRatesIdPayRates" }, "fk_Employee_Pay Rates");

                    b.ToTable("employee");
                });

            modelBuilder.Entity("DashBoard.API.Models.PayRate", b =>
                {
                    b.Property<int>("IdPayRates")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idPay Rates");

                    b.Property<decimal>("PayAmount")
                        .HasColumnType("decimal(10,0)")
                        .HasColumnName("Pay Amount");

                    b.Property<string>("PayRateName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("Pay Rate Name");

                    b.Property<int>("PayType")
                        .HasColumnType("int")
                        .HasColumnName("Pay Type");

                    b.Property<decimal>("PtLevelC")
                        .HasColumnType("decimal(10,0)")
                        .HasColumnName("PT - Level C");

                    b.Property<decimal>("TaxPercentage")
                        .HasColumnType("decimal(10,0)")
                        .HasColumnName("Tax Percentage");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(10,0)");

                    b.HasKey("IdPayRates");

                    b.ToTable("pay rates");
                });

            modelBuilder.Entity("DashBoard.API.Models.Employee", b =>
                {
                    b.HasOne("DashBoard.API.Models.PayRate", "PayRatesIdPayRatesNavigation")
                        .WithMany("Employees")
                        .HasForeignKey("PayRatesIdPayRates")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PayRatesIdPayRatesNavigation");
                });

            modelBuilder.Entity("DashBoard.API.Models.PayRate", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
